/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.ControladorCliente;
import controlador.ControladorEventos;
import controlador.ControladorInscripcion;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.Cliente;
import logica.Inscripcion;
import logica.Usuario;

/**
 *
 * @author Alexandra
 */
public class registrarInscripcion extends javax.swing.JFrame {

    ControladorCliente controladorCliente;
    interfazOperario interfazOper;
    ControladorEventos controladorEvento;
    ControladorInscripcion controladorInscripcion;

    /**
     * Creates new form crearCliente
     */
    public registrarInscripcion(Usuario u) {
        initComponents();
        controladorInscripcion = new ControladorInscripcion();
        controladorCliente = new ControladorCliente();

        controladorEvento = new ControladorEventos();
        this.setLocationRelativeTo(null);
        interfazOper = new interfazOperario(u);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CargarEventos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        eventoCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        id_cliente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Evento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        CargarEventos.setText("Eventos");
        CargarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarEventosActionPerformed(evt);
            }
        });
        getContentPane().add(CargarEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, 20));

        jButton1.setText("Registrar preinscripcion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 160, -1));

        getContentPane().add(eventoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Identificacion cliente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        id_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(id_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 150, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Registrar Preinscripcion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jButton2))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/cash-register.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 70, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/operator (4).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/booking.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 70, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/note.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 70, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/bulb (1).png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 60, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/operator (2).png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 60, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/jj.jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (validar()) {
            Inscripcion in = new Inscripcion();
            in.setIdCliente(id_cliente.getText());
            in.setIdEvento(eventoCombo.getSelectedItem().toString());
            in.setPago("no");
            boolean seAgrego = controladorInscripcion.agregarInscripcion(in);
            if (seAgrego) {
                
                JOptionPane.showMessageDialog(this, "Se agrego la preinscripcion a la base de datos", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            } else {
                Icon p = new ImageIcon(getClass().getResource("/gui/images/x.png"));
                JOptionPane.showMessageDialog(this, "Hubo un error al agregar la preinscripcion ", "", JOptionPane.INFORMATION_MESSAGE, p);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean validar() {
        boolean rest = true;
        if (sololetras(id_cliente.getText()) || id_cliente.getText().equals("")) {
            rest = false;
            id_cliente.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Por favor verifique la identificación del cliente", "", JOptionPane.INFORMATION_MESSAGE);
            return rest;
        }

        if (!controladorCliente.existeCliente(id_cliente.getText())) {
            rest = false;
            JOptionPane.showMessageDialog(this, "El cliente no existe", "", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
            return rest;
        }
        if (eventoCombo.getSelectedIndex() == -1) {
            Icon p = new ImageIcon(getClass().getResource("/gui/images/x.png"));

            JOptionPane.showMessageDialog(this, " Debe seleccionar entre los eventos disponibles", "", JOptionPane.INFORMATION_MESSAGE, p);

            rest = false;
            return rest;
        }
        if (controladorInscripcion.existeInscripcion(id_cliente.getText(), eventoCombo.getSelectedItem().toString())) {
            rest = false;
            JOptionPane.showMessageDialog(this, "El cliente ya se encuentra preinscrito a este evento", "", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
            return rest;
        }

        

        return rest;
    }

    public static boolean sololetras(String prueba) {
        boolean result = false;
        String comparacion = "!!#$%&/()=?¡*¨][_:;°¬|@·~½¬{[]}~─µ";
        for (int i = prueba.length() - 1; i >= 0; i--) {
            for (int j = comparacion.length() - 1; j >= 0; j--) {
                if (prueba.charAt(i) == comparacion.charAt(j)) {
                    result = true;
                    return result;
                }
            }
        }
        return result;
    }

    public void limpiar() {
        id_cliente.setText("");
        eventoCombo.removeAllItems();
        id_cliente.setBackground(Color.white);
    }


    private void id_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_clienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        interfazOper.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CargarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarEventosActionPerformed
        eventoCombo.removeAllItems();
        ArrayList<String> ve = new ArrayList<String>();
        ve = controladorEvento.retornar();
        eventoCombo.addItem("");

        for (int i = 0; i < ve.size(); i++) {

            String item;
            item = ve.get(i);
            eventoCombo.addItem(item);
            item = "";
        }

    }//GEN-LAST:event_CargarEventosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarEventos;
    private javax.swing.JComboBox<String> eventoCombo;
    private javax.swing.JTextField id_cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
