/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.ControladorEventos;
import controlador.ControladorReportes;
import datechooser.beans.DateChooserCombo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author tovar
 */
public class ReportePreinscripcionesYPagos extends javax.swing.JFrame {
    private String textoDir = "Seleccione un directorio por favor....";
    private ControladorReportes controladorReportes;
    private DateChooserCombo hoy;
    /**
     * Creates new form ReportePreinscripcionesYPagos
     */
    
    ActionListener sliceActionListener = new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        AbstractButton aButton = (AbstractButton) actionEvent.getSource();
        System.out.println("Selected: " + aButton.getText());
        desde.setEnabled(true);
        hasta.setEnabled(true);
        buscarRuta.setEnabled(true);
      }
    };

    
    public ReportePreinscripcionesYPagos() {
        initComponents();
        pagos.addActionListener(sliceActionListener);
        nopagos.addActionListener(sliceActionListener);
        pagosynopagos.addActionListener(sliceActionListener);
        
        ruta.setText(textoDir);
        controladorReportes = new ControladorReportes();
        hoy = desde;
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        desde = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hasta = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        pagos = new javax.swing.JRadioButton();
        nopagos = new javax.swing.JRadioButton();
        pagosynopagos = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        buscarRuta = new javax.swing.JButton();
        ruta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        generarReporte = new javax.swing.JButton();
        nombreArchivo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desde.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                desdeOnSelectionChange(evt);
            }
        });

        jLabel1.setText("Desde:");

        jLabel2.setText("Hasta:");

        hasta.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                hastaOnSelectionChange(evt);
            }
        });

        jLabel3.setText("Tipo reporte:");

        buttonGroup1.add(pagos);
        pagos.setText("Pagos");

        buttonGroup1.add(nopagos);
        nopagos.setText("No pagos");

        buttonGroup1.add(pagosynopagos);
        pagosynopagos.setText("Pagos y No Pagos");

        jLabel4.setText("Destino Reporte:");

        buscarRuta.setText("Buscar Ruta Reporte");
        buscarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarRutaActionPerformed(evt);
            }
        });

        ruta.setText("Aqui se escribe la ruta");

        jLabel6.setText("Nombre del archivo:");

        generarReporte.setText("Generar reporte");
        generarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarReporteActionPerformed(evt);
            }
        });

        nombreArchivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreArchivoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreArchivoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreArchivoKeyReleased(evt);
            }
        });

        jButton3.setText("LImpiar todo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pagos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nopagos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagosynopagos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(ruta))
                            .addComponent(nombreArchivo)
                            .addComponent(buscarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generarReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagos)
                    .addComponent(nopagos)
                    .addComponent(pagosynopagos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(buscarRuta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generarReporte)
                    .addComponent(jButton3))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarRutaActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); //solo carpetas
        filechooser.setAcceptAllFileFilterUsed(false);
        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            ruta.setText(filechooser.getSelectedFile().toString());
            nombreArchivo.setEditable(true);
            nombreArchivo.setEnabled(true);
            System.out.println("getCurrentDirectory(): " +  filechooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : " +  filechooser.getSelectedFile());
        }else{
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_buscarRutaActionPerformed

    private void nombreArchivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreArchivoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_nombreArchivoKeyPressed

    private void nombreArchivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreArchivoKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_nombreArchivoKeyTyped

    private void nombreArchivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreArchivoKeyReleased
        // TODO add your handling code here:
        
        //validar nombre archivo aqui
        if(!nombreArchivo.getText().equals("")){
            generarReporte.setEnabled(true);
        }else{
           generarReporte.setEnabled(false);
        }
    }//GEN-LAST:event_nombreArchivoKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void generarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarReporteActionPerformed
        // TODO add your handling code here:

        if (validarFechas()) {
            boolean guardo = false;
            java.util.Date fechaDesde = desde.getSelectedDate().getTime();
            java.util.Date fechaHasta = hasta.getSelectedDate().getTime();

            java.sql.Date desdeSql = new java.sql.Date(fechaDesde.getTime());
            java.sql.Date hastaSql = new java.sql.Date(fechaHasta.getTime());

            String rutaArchivo = ruta.getText();
            String nombre = nombreArchivo.getText();
            for (Enumeration<AbstractButton> buttons = buttonGroup1.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();
                if (button.isSelected()) {
                    if (button.equals(pagos)) {
                        guardo = controladorReportes.reportePagos(rutaArchivo, nombre, desdeSql, hastaSql);
                    } else if (button.equals(nopagos)) {
                        guardo = controladorReportes.reporteNoPagos(rutaArchivo, nombre, desdeSql, hastaSql);
                    } else if (button.equals(pagosynopagos)) {
                        guardo = controladorReportes.reportePagosYNoPagos(rutaArchivo, nombre, desdeSql, hastaSql);
                    }
                }
            }

            if (guardo) {
                JOptionPane.showMessageDialog(this, "El reporte se guardo correctamente", "", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Hubo un error al itentar crear el reporte, revise que el nombre del archivo y la ruta sean validas o que si el archivo ya existe que no este abierto", "", JOptionPane.ERROR_MESSAGE);
            }

        }
        

    }//GEN-LAST:event_generarReporteActionPerformed

    private void hastaOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_hastaOnSelectionChange
        // TODO add your handling code here:
    }//GEN-LAST:event_hastaOnSelectionChange

    private void desdeOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_desdeOnSelectionChange
        // TODO add your handling code here:
    }//GEN-LAST:event_desdeOnSelectionChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportePreinscripcionesYPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportePreinscripcionesYPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportePreinscripcionesYPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportePreinscripcionesYPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportePreinscripcionesYPagos().setVisible(true);
            }
        });
    }
    
    private void limpiar() {
        buttonGroup1.clearSelection(); // limpiamos los radio
        desde.setEnabled(false);
        hasta.setEnabled(false);
        
        buscarRuta.setEnabled(false);
        nombreArchivo.setEnabled(false);
        nombreArchivo.setEditable(false);
        generarReporte.setEnabled(false);
        nombreArchivo.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarRuta;
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo desde;
    private javax.swing.JButton generarReporte;
    private datechooser.beans.DateChooserCombo hasta;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombreArchivo;
    private javax.swing.JRadioButton nopagos;
    private javax.swing.JRadioButton pagos;
    private javax.swing.JRadioButton pagosynopagos;
    private javax.swing.JLabel ruta;
    // End of variables declaration//GEN-END:variables

    private boolean validarFechas() {
        if(desde.getSelectedDate().getTime().getTime()>hasta.getSelectedDate().getTime().getTime()){
            desde = hoy;
            hasta = hoy;
            JOptionPane.showMessageDialog(this, "La primera fecha no puede ser mayor que la segunda, cambiela", "", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }
}
