/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.ControladorEventos;
import controlador.ControladorReportes;
import datechooser.beans.DateChooserCombo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import logica.Usuario;

/**
 *
 * @author tovar
 */
public class ReportePreinscripcionesYPagos extends javax.swing.JFrame {
    private String textoDir = "Seleccione un directorio por favor....";
    private ControladorReportes controladorReportes;
    private DateChooserCombo hoy;
    private interfazGerente interfazgerente;
    /**
     * Creates new form ReportePreinscripcionesYPagos
     */
    
    ActionListener sliceActionListener = new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        AbstractButton aButton = (AbstractButton) actionEvent.getSource();
        System.out.println("Selected: " + aButton.getText());
        desde.setEnabled(true);
        hasta.setEnabled(true);
        buscarRuta.setEnabled(true);
      }
    };

    
    public ReportePreinscripcionesYPagos(Usuario u) {
        initComponents();
        pagos.addActionListener(sliceActionListener);
        nopagos.addActionListener(sliceActionListener);
        pagosynopagos.addActionListener(sliceActionListener);
        
        ruta.setText(textoDir);
        controladorReportes = new ControladorReportes();
        hoy = desde;
        limpiar();
        interfazgerente = new interfazGerente(u);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        desde = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hasta = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        pagos = new javax.swing.JRadioButton();
        nopagos = new javax.swing.JRadioButton();
        pagosynopagos = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        buscarRuta = new javax.swing.JButton();
        ruta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        generarReporte = new javax.swing.JButton();
        nombreArchivo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desde.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                desdeOnSelectionChange(evt);
            }
        });
        getContentPane().add(desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel1.setText("Desde:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel2.setText("Hasta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        hasta.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                hastaOnSelectionChange(evt);
            }
        });
        getContentPane().add(hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tipo reporte:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        buttonGroup1.add(pagos);
        pagos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pagos.setText("Pagos");
        getContentPane().add(pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        buttonGroup1.add(nopagos);
        nopagos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nopagos.setText("No pagos");
        getContentPane().add(nopagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        buttonGroup1.add(pagosynopagos);
        pagosynopagos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pagosynopagos.setText("Pagos y No Pagos");
        getContentPane().add(pagosynopagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Destino Reporte:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        buscarRuta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buscarRuta.setText("Buscar Ruta Reporte");
        buscarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarRutaActionPerformed(evt);
            }
        });
        getContentPane().add(buscarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        ruta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ruta.setText("Aqui se escribe la ruta");
        getContentPane().add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Nombre del archivo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        generarReporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        generarReporte.setText("Generar reporte");
        generarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(generarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        nombreArchivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nombreArchivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreArchivoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreArchivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreArchivoKeyTyped(evt);
            }
        });
        getContentPane().add(nombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 133, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("LImpiar todo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Reporte evento");

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.setText("Atras");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/gradient-1227798_960_720.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarRutaActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); //solo carpetas
        filechooser.setAcceptAllFileFilterUsed(false);
        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            ruta.setText(filechooser.getSelectedFile().toString());
            nombreArchivo.setEditable(true);
            nombreArchivo.setEnabled(true);
            System.out.println("getCurrentDirectory(): " +  filechooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : " +  filechooser.getSelectedFile());
        }else{
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_buscarRutaActionPerformed

    private void nombreArchivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreArchivoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_nombreArchivoKeyPressed

    private void nombreArchivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreArchivoKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_nombreArchivoKeyTyped

    private void nombreArchivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreArchivoKeyReleased
        // TODO add your handling code here:
        
        //validar nombre archivo aqui
        if(!nombreArchivo.getText().equals("")){
            generarReporte.setEnabled(true);
        }else{
           generarReporte.setEnabled(false);
        }
    }//GEN-LAST:event_nombreArchivoKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void generarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarReporteActionPerformed
        // TODO add your handling code here:

        if (validarFechas()) {
            boolean guardo = false;
            java.util.Date fechaDesde = desde.getSelectedDate().getTime();
            java.util.Date fechaHasta = hasta.getSelectedDate().getTime();

            java.sql.Date desdeSql = new java.sql.Date(fechaDesde.getTime());
            java.sql.Date hastaSql = new java.sql.Date(fechaHasta.getTime());

            String rutaArchivo = ruta.getText();
            String nombre = nombreArchivo.getText();
            for (Enumeration<AbstractButton> buttons = buttonGroup1.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();
                if (button.isSelected()) {
                    if (button.equals(pagos)) {
                        guardo = controladorReportes.reportePagos(rutaArchivo, nombre, desdeSql, hastaSql);
                    } else if (button.equals(nopagos)) {
                        guardo = controladorReportes.reporteNoPagos(rutaArchivo, nombre, desdeSql, hastaSql);
                    } else if (button.equals(pagosynopagos)) {
                        guardo = controladorReportes.reportePagosYNoPagos(rutaArchivo, nombre, desdeSql, hastaSql);
                    }
                }
            }

            if (guardo) {
                JOptionPane.showMessageDialog(this, "El reporte se guardo correctamente", "", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Hubo un error al itentar crear el reporte, revise que el nombre del archivo y la ruta sean validas o que si el archivo ya existe que no este abierto", "", JOptionPane.ERROR_MESSAGE);
            }

        }
        

    }//GEN-LAST:event_generarReporteActionPerformed

    private void hastaOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_hastaOnSelectionChange
        // TODO add your handling code here:
    }//GEN-LAST:event_hastaOnSelectionChange

    private void desdeOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_desdeOnSelectionChange
        // TODO add your handling code here:
    }//GEN-LAST:event_desdeOnSelectionChange

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        interfazgerente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    
    private void limpiar() {
        buttonGroup1.clearSelection(); // limpiamos los radio
        desde.setEnabled(false);
        hasta.setEnabled(false);
        
        buscarRuta.setEnabled(false);
        nombreArchivo.setEnabled(false);
        nombreArchivo.setEditable(false);
        generarReporte.setEnabled(false);
        nombreArchivo.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarRuta;
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo desde;
    private javax.swing.JButton generarReporte;
    private datechooser.beans.DateChooserCombo hasta;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreArchivo;
    private javax.swing.JRadioButton nopagos;
    private javax.swing.JRadioButton pagos;
    private javax.swing.JRadioButton pagosynopagos;
    private javax.swing.JLabel ruta;
    // End of variables declaration//GEN-END:variables

    private boolean validarFechas() {
        if(desde.getSelectedDate().getTime().getTime()>hasta.getSelectedDate().getTime().getTime()){
            desde = hoy;
            hasta = hoy;
            JOptionPane.showMessageDialog(this, "La primera fecha no puede ser mayor que la segunda, cambiela", "", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }
}
